In [272]:
import pandas as pd
import numpy as np
import math
from scipy.stats import entropy
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.ensemble import ExtraTreesRegressor
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder
import warnings
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn import datasets, tree, metrics, model_selection, svm
warnings.filterwarnings('ignore')

In [167]:
def injectNaN(x):
    if x == "_T":
        return np.nan
    else: 
        return x

In [168]:
def printDFInfo(df):
    for col in df.columns:
        ent = entropy(df[col].value_counts())
        if col == 'TOPIC':
            print(f'Column \"{col}\"\t\tΜissing values: {(df[col].isnull().sum() * 100 / len(df[col])):.2f}% || Entropy: {ent:.3f}')
        else:
            print(f'Column \"{col}\"\tΜissing values: {(df[col].isnull().sum() * 100 / len(df[col])):.2f}% || Entropy: {ent:.3f}')

In [169]:
data = pd.read_csv('VAW.csv')
data.head()

,DATAFLOW,FREQ: Frequency,TIME_PERIOD: Time,GEO_PICT: Pacific Island Countries and territories,TOPIC: Topic,INDICATOR: Indicator,SEX: Sex,AGE: Age,CONDITION: Women’s condition,VIOLENCE_TYPE: Type of violence,...,OUTCOME: Outcome,RESPONSE: Response,HELP_REASON: Reason for searching help,HELP_PROVIDER: Help provider,OBS_VALUE,UNIT_MEASURE: Unit of measure,UNIT_MULT: Unit multiplier,OBS_STATUS: Observation Status,DATA_SOURCE: Data source,OBS_COMMENT: Comment
0,SPC:DF_VAW(1.0),A: Annual,2013,CK: Cook Islands,VAW_TOPIC_001: Types of violence against women...,NUMPERRF: Number of persons in relative frequency,F: Female,Y15T64: 15-64,EVPART: Ever-partnered,CONT_ECON: At least one act of economic abusive,...,_T: Any,_T: Any,_T: Any,_T: Any,6.2,PERCENT: percent,NaN,NaN,FHSS,NaN
1,SPC:DF_VAW(1.0),A: Annual,2013,CK: Cook Islands,VAW_TOPIC_001: Types of violence against women...,NUMPERRF: Number of persons in relative frequency,F: Female,Y15T64: 15-64,EVPART: Ever-partnered,EMO: Emotional violence,...,_T: Any,_T: Any,_T: Any,_T: Any,9.6,PERCENT: percent,NaN,NaN,FHSS,NaN
2,SPC:DF_VAW(1.0),A: Annual,2013,CK: Cook Islands,VAW_TOPIC_001: Types of violence against women...,NUMPERRF: Number of persons in relative frequency,F: Female,Y15T64: 15-64,EVPART: Ever-partnered,EMO: Emotional violence,...,_T: Any,_T: Any,_T: Any,_T: Any,26.7,PERCENT: percent,NaN,NaN,FHSS,NaN
3,SPC:DF_VAW(1.0),A: Annual,2013,CK: Cook Islands,VAW_TOPIC_001: Types of violence against women...,NUMPERRF: Number of persons in relative frequency,F: Female,Y15T64: 15-64,EVPART: Ever-partnered,PHYS: Physical violence,...,_T: Any,_T: Any,_T: Any,_T: Any,6.7,PERCENT: percent,NaN,NaN,FHSS,NaN
4,SPC:DF_VAW(1.0),A: Annual,2013,CK: Cook Islands,VAW_TOPIC_001: Types of violence against women...,NUMPERRF: Number of persons in relative frequency,F: Female,Y15T64: 15-64,EVPART: Ever-partnered,PHYS: Physical violence,...,_T: Any,_T: Any,_T: Any,_T: Any,30.2,PERCENT: percent,NaN,NaN,FHSS,NaN

In [170]:
data.columns = data.columns.to_series().apply(lambda x: x.split(':')[0])

for col in data.columns:
    try:
        data[col] = data[col].apply(lambda x: x.split(':')[0])
        data[col] = data[col].apply(injectNaN)
    except AttributeError:
        pass
    
data.head()

,DATAFLOW,FREQ,TIME_PERIOD,GEO_PICT,TOPIC,INDICATOR,SEX,AGE,CONDITION,VIOLENCE_TYPE,...,OUTCOME,RESPONSE,HELP_REASON,HELP_PROVIDER,OBS_VALUE,UNIT_MEASURE,UNIT_MULT,OBS_STATUS,DATA_SOURCE,OBS_COMMENT
0,SPC,A,2013,CK,VAW_TOPIC_001,NUMPERRF,F,Y15T64,EVPART,CONT_ECON,...,NaN,NaN,NaN,NaN,6.2,PERCENT,NaN,NaN,FHSS,NaN
1,SPC,A,2013,CK,VAW_TOPIC_001,NUMPERRF,F,Y15T64,EVPART,EMO,...,NaN,NaN,NaN,NaN,9.6,PERCENT,NaN,NaN,FHSS,NaN
2,SPC,A,2013,CK,VAW_TOPIC_001,NUMPERRF,F,Y15T64,EVPART,EMO,...,NaN,NaN,NaN,NaN,26.7,PERCENT,NaN,NaN,FHSS,NaN
3,SPC,A,2013,CK,VAW_TOPIC_001,NUMPERRF,F,Y15T64,EVPART,PHYS,...,NaN,NaN,NaN,NaN,6.7,PERCENT,NaN,NaN,FHSS,NaN
4,SPC,A,2013,CK,VAW_TOPIC_001,NUMPERRF,F,Y15T64,EVPART,PHYS,...,NaN,NaN,NaN,NaN,30.2,PERCENT,NaN,NaN,FHSS,NaN

In [171]:
dropList = []

for col in data.columns:
    ent = entropy(data[col].value_counts())
    if ent == 0:
        dropList.append(col)
        print(f'Column \"{col}\" entropy: {ent:.2f} || ADDED TO DROPLIST')
    else:
        print(f'Column \"{col}\" entropy: {ent:.2f}')

Column "DATAFLOW" entropy: 0.00 || ADDED TO DROPLIST
Column "FREQ" entropy: 0.00 || ADDED TO DROPLIST
Column "TIME_PERIOD" entropy: 2.25
Column "GEO_PICT" entropy: 2.51
Column "TOPIC" entropy: 2.83
Column "INDICATOR" entropy: 0.00 || ADDED TO DROPLIST
Column "SEX" entropy: 0.00 || ADDED TO DROPLIST
Column "AGE" entropy: 0.00 || ADDED TO DROPLIST
Column "CONDITION" entropy: 0.90
Column "VIOLENCE_TYPE" entropy: 2.74
Column "PERPETRATOR" entropy: 0.99
Column "ACTUALITY" entropy: 0.69
Column "LIFEPER" entropy: 0.82
Column "OUTCOME" entropy: 3.05
Column "RESPONSE" entropy: 1.95
Column "HELP_REASON" entropy: 1.79
Column "HELP_PROVIDER" entropy: 1.61
Column "OBS_VALUE" entropy: 5.95
Column "UNIT_MEASURE" entropy: 0.00 || ADDED TO DROPLIST
Column "UNIT_MULT" entropy: 0.00 || ADDED TO DROPLIST
Column "OBS_STATUS" entropy: 0.00 || ADDED TO DROPLIST
Column "DATA_SOURCE" entropy: 1.45
Column "OBS_COMMENT" entropy: 1.81

In [172]:
data.drop(dropList, axis = 1, inplace = True)
printDFInfo(data)

Column "TIME_PERIOD"	Μissing values: 0.00% || Entropy: 2.253
Column "GEO_PICT"	Μissing values: 0.00% || Entropy: 2.513
Column "TOPIC"		Μissing values: 0.00% || Entropy: 2.833
Column "CONDITION"	Μissing values: 52.38% || Entropy: 0.900
Column "VIOLENCE_TYPE"	Μissing values: 34.92% || Entropy: 2.744
Column "PERPETRATOR"	Μissing values: 12.70% || Entropy: 0.992
Column "ACTUALITY"	Μissing values: 41.27% || Entropy: 0.692
Column "LIFEPER"	Μissing values: 76.19% || Entropy: 0.817
Column "OUTCOME"	Μissing values: 73.02% || Entropy: 3.047
Column "RESPONSE"	Μissing values: 94.44% || Entropy: 1.946
Column "HELP_REASON"	Μissing values: 95.24% || Entropy: 1.792
Column "HELP_PROVIDER"	Μissing values: 96.03% || Entropy: 1.609
Column "OBS_VALUE"	Μissing values: 38.79% || Entropy: 5.948
Column "DATA_SOURCE"	Μissing values: 0.00% || Entropy: 1.450
Column "OBS_COMMENT"	Μissing values: 49.75% || Entropy: 1.807

In [173]:
print(data.shape)

(2016, 15)

In [174]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2016 entries, 0 to 2015
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   TIME_PERIOD    2016 non-null   int64
 1   GEO_PICT       2016 non-null   object
 2   TOPIC          2016 non-null   object
 3   CONDITION      960 non-null    object
 4   VIOLENCE_TYPE  1312 non-null   object
 5   PERPETRATOR    1760 non-null   object
 6   ACTUALITY      1184 non-null   object
 7   LIFEPER        480 non-null    object
 8   OUTCOME        544 non-null    object
 9   RESPONSE       112 non-null    object
 10  HELP_REASON    96 non-null     object
 11  HELP_PROVIDER  80 non-null     object
 12  OBS_VALUE      1234 non-null   float64
 13  DATA_SOURCE    2016 non-null   object
 14  OBS_COMMENT    1013 non-null   object
dtypes: float64(1), int64(1), object(13)
memory usage: 236.4+ KB

In [175]:
encode_data = data

In [176]:
data_train_idx = []
data_test_idx = []

for index, row in data.iterrows():
    if (type(row['OUTCOME']) == float):
        data_test_idx.append(index)
    else:
        data_train_idx.append(index)

In [177]:
data_train = data.iloc[data_train_idx,:] 
data_test = data.iloc[data_test_idx,:] 

data_train.reset_index(drop = True, inplace = True)
data_test.reset_index(drop = True, inplace = True)

print(data_train.shape)
print(data_test.shape)

(544, 15)
(1472, 15)

In [178]:
printDFInfo(data_train)

Column "TIME_PERIOD"	Μissing values: 0.00% || Entropy: 2.253
Column "GEO_PICT"	Μissing values: 0.00% || Entropy: 2.513
Column "TOPIC"		Μissing values: 0.00% || Entropy: 1.568
Column "CONDITION"	Μissing values: 52.94% || Entropy: 1.082
Column "VIOLENCE_TYPE"	Μissing values: 73.53% || Entropy: 0.995
Column "PERPETRATOR"	Μissing values: 26.47% || Entropy: 0.000
Column "ACTUALITY"	Μissing values: 73.53% || Entropy: 0.687
Column "LIFEPER"	Μissing values: 91.18% || Entropy: 0.000
Column "OUTCOME"	Μissing values: 0.00% || Entropy: 3.047
Column "RESPONSE"	Μissing values: 100.00% || Entropy: 0.000
Column "HELP_REASON"	Μissing values: 100.00% || Entropy: 0.000
Column "HELP_PROVIDER"	Μissing values: 100.00% || Entropy: 0.000
Column "OBS_VALUE"	Μissing values: 45.22% || Entropy: 5.223
Column "DATA_SOURCE"	Μissing values: 0.00% || Entropy: 1.450
Column "OBS_COMMENT"	Μissing values: 50.00% || Entropy: 1.800

In [179]:
printDFInfo(data_test)

Column "TIME_PERIOD"	Μissing values: 0.00% || Entropy: 2.253
Column "GEO_PICT"	Μissing values: 0.00% || Entropy: 2.513
Column "TOPIC"		Μissing values: 0.00% || Entropy: 2.501
Column "CONDITION"	Μissing values: 52.17% || Entropy: 0.108
Column "VIOLENCE_TYPE"	Μissing values: 20.65% || Entropy: 2.819
Column "PERPETRATOR"	Μissing values: 7.61% || Entropy: 1.179
Column "ACTUALITY"	Μissing values: 29.35% || Entropy: 0.692
Column "LIFEPER"	Μissing values: 70.65% || Entropy: 0.630
Column "OUTCOME"	Μissing values: 100.00% || Entropy: 0.000
Column "RESPONSE"	Μissing values: 92.39% || Entropy: 1.946
Column "HELP_REASON"	Μissing values: 93.48% || Entropy: 1.792
Column "HELP_PROVIDER"	Μissing values: 94.57% || Entropy: 1.609
Column "OBS_VALUE"	Μissing values: 36.41% || Entropy: 5.851
Column "DATA_SOURCE"	Μissing values: 0.00% || Entropy: 1.450
Column "OBS_COMMENT"	Μissing values: 49.66% || Entropy: 1.790

In [180]:
dropList = []

for col in data_train.columns:
    ent = entropy(data_train[col].value_counts())
    if ent == 0:
        dropList.append(col)
        print(f'Column \"{col}\" entropy: {ent:.2f} || ADDED TO DROPLIST')
    else:
        print(f'Column \"{col}\" entropy: {ent:.2f}')

Column "TIME_PERIOD" entropy: 2.25
Column "GEO_PICT" entropy: 2.51
Column "TOPIC" entropy: 1.57
Column "CONDITION" entropy: 1.08
Column "VIOLENCE_TYPE" entropy: 1.00
Column "PERPETRATOR" entropy: 0.00 || ADDED TO DROPLIST
Column "ACTUALITY" entropy: 0.69
Column "LIFEPER" entropy: 0.00 || ADDED TO DROPLIST
Column "OUTCOME" entropy: 3.05
Column "RESPONSE" entropy: 0.00 || ADDED TO DROPLIST
Column "HELP_REASON" entropy: 0.00 || ADDED TO DROPLIST
Column "HELP_PROVIDER" entropy: 0.00 || ADDED TO DROPLIST
Column "OBS_VALUE" entropy: 5.22
Column "DATA_SOURCE" entropy: 1.45
Column "OBS_COMMENT" entropy: 1.80

In [181]:
data_train.drop(dropList, axis = 1, inplace = True)
data_test.drop(dropList, axis = 1, inplace = True)

In [182]:
printDFInfo(data_train)

Column "TIME_PERIOD"	Μissing values: 0.00% || Entropy: 2.253
Column "GEO_PICT"	Μissing values: 0.00% || Entropy: 2.513
Column "TOPIC"		Μissing values: 0.00% || Entropy: 1.568
Column "CONDITION"	Μissing values: 52.94% || Entropy: 1.082
Column "VIOLENCE_TYPE"	Μissing values: 73.53% || Entropy: 0.995
Column "ACTUALITY"	Μissing values: 73.53% || Entropy: 0.687
Column "OUTCOME"	Μissing values: 0.00% || Entropy: 3.047
Column "OBS_VALUE"	Μissing values: 45.22% || Entropy: 5.223
Column "DATA_SOURCE"	Μissing values: 0.00% || Entropy: 1.450
Column "OBS_COMMENT"	Μissing values: 50.00% || Entropy: 1.800

In [183]:
printDFInfo(data_test)

Column "TIME_PERIOD"	Μissing values: 0.00% || Entropy: 2.253
Column "GEO_PICT"	Μissing values: 0.00% || Entropy: 2.513
Column "TOPIC"		Μissing values: 0.00% || Entropy: 2.501
Column "CONDITION"	Μissing values: 52.17% || Entropy: 0.108
Column "VIOLENCE_TYPE"	Μissing values: 20.65% || Entropy: 2.819
Column "ACTUALITY"	Μissing values: 29.35% || Entropy: 0.692
Column "OUTCOME"	Μissing values: 100.00% || Entropy: 0.000
Column "OBS_VALUE"	Μissing values: 36.41% || Entropy: 5.851
Column "DATA_SOURCE"	Μissing values: 0.00% || Entropy: 1.450
Column "OBS_COMMENT"	Μissing values: 49.66% || Entropy: 1.790

In [184]:
data_train.to_csv("data_train.csv", index = False)
data_test.to_csv("data_test.csv", index = False)

In [185]:
#encoding below----------------------------------------------------------------------------------

#instantiate both packages to use
encoder = OrdinalEncoder()
imputer = IterativeImputer(ExtraTreesRegressor())
# create a list of categorical columns to iterate over
cat_cols = ['GEO_PICT','TOPIC','CONDITION','VIOLENCE_TYPE','PERPETRATOR','ACTUALITY','LIFEPER', 
            'OUTCOME', 'RESPONSE','HELP_REASON', 'HELP_PROVIDER', 'DATA_SOURCE', 'OBS_COMMENT']

def encode(encode_data):
    '''function to encode non-null data and replace it in the original data'''
    #retains only non-null values
    nonulls = np.array(encode_data.dropna())
    #reshapes the data for encoding
    impute_reshape = nonulls.reshape(-1,1)
    #encode date
    impute_ordinal = encoder.fit_transform(impute_reshape)
    #Assign back encoded values to non-null values
    encode_data.loc[encode_data.notnull()] = np.squeeze(impute_ordinal)
    return encode_data

for columns in cat_cols:
    encode(encode_data[columns])
    
encode_data.head(100)

,TIME_PERIOD,GEO_PICT,TOPIC,CONDITION,VIOLENCE_TYPE,PERPETRATOR,ACTUALITY,LIFEPER,OUTCOME,RESPONSE,HELP_REASON,HELP_PROVIDER,OBS_VALUE,DATA_SOURCE,OBS_COMMENT
0,2013,0.0,0.0,1.0,0.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,6.2,1.0,NaN
1,2013,0.0,0.0,1.0,5.0,5.0,0.0,NaN,NaN,NaN,NaN,NaN,9.6,1.0,NaN
2,2013,0.0,0.0,1.0,5.0,5.0,1.0,NaN,NaN,NaN,NaN,NaN,26.7,1.0,NaN
3,2013,0.0,0.0,1.0,9.0,5.0,0.0,NaN,NaN,NaN,NaN,NaN,6.7,1.0,NaN
4,2013,0.0,0.0,1.0,9.0,5.0,1.0,NaN,NaN,NaN,NaN,NaN,30.2,1.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2013,0.0,12.0,2.0,NaN,5.0,NaN,1.0,0.0,NaN,NaN,NaN,3.6,1.0,NaN
96,2013,0.0,12.0,2.0,NaN,5.0,NaN,1.0,16.0,NaN,NaN,NaN,8.9,1.0,NaN
97,2013,0.0,12.0,2.0,NaN,5.0,NaN,1.0,21.0,NaN,NaN,NaN,8.8,1.0,NaN
98,2013,0.0,13.0,3.0,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,1.0,NaN
99,2013,0.0,13.0,3.0,NaN,NaN,NaN,NaN,14.0,NaN,NaN,NaN,NaN,1.0,NaN

In [186]:
data_enc_train_idx = []
data_enc_test_idx = []

for index, row in encode_data.iterrows():
    if (math.isnan(row['OUTCOME'])): #== NaN
        data_enc_test_idx.append(index)
    else:
        data_enc_train_idx.append(index)

In [187]:
data_enc_train = encode_data.iloc[data_enc_train_idx,:] 
data_enc_test = encode_data.iloc[data_enc_test_idx,:] 

data_enc_train.reset_index(drop = True, inplace = True)
data_enc_test.reset_index(drop = True, inplace = True)

print(data_enc_train.shape)
print(data_enc_test.shape)

(544, 15)
(1472, 15)

In [188]:
printDFInfo(data_enc_train)

Column "TIME_PERIOD"	Μissing values: 0.00% || Entropy: 2.253
Column "GEO_PICT"	Μissing values: 0.00% || Entropy: 2.513
Column "TOPIC"		Μissing values: 0.00% || Entropy: 1.568
Column "CONDITION"	Μissing values: 52.94% || Entropy: 1.082
Column "VIOLENCE_TYPE"	Μissing values: 73.53% || Entropy: 0.995
Column "PERPETRATOR"	Μissing values: 26.47% || Entropy: 0.000
Column "ACTUALITY"	Μissing values: 73.53% || Entropy: 0.687
Column "LIFEPER"	Μissing values: 91.18% || Entropy: 0.000
Column "OUTCOME"	Μissing values: 0.00% || Entropy: 3.047
Column "RESPONSE"	Μissing values: 100.00% || Entropy: 0.000
Column "HELP_REASON"	Μissing values: 100.00% || Entropy: 0.000
Column "HELP_PROVIDER"	Μissing values: 100.00% || Entropy: 0.000
Column "OBS_VALUE"	Μissing values: 45.22% || Entropy: 5.223
Column "DATA_SOURCE"	Μissing values: 0.00% || Entropy: 1.450
Column "OBS_COMMENT"	Μissing values: 50.00% || Entropy: 1.800

In [189]:
printDFInfo(data_enc_test)

Column "TIME_PERIOD"	Μissing values: 0.00% || Entropy: 2.253
Column "GEO_PICT"	Μissing values: 0.00% || Entropy: 2.513
Column "TOPIC"		Μissing values: 0.00% || Entropy: 2.501
Column "CONDITION"	Μissing values: 52.17% || Entropy: 0.108
Column "VIOLENCE_TYPE"	Μissing values: 20.65% || Entropy: 2.819
Column "PERPETRATOR"	Μissing values: 7.61% || Entropy: 1.179
Column "ACTUALITY"	Μissing values: 29.35% || Entropy: 0.692
Column "LIFEPER"	Μissing values: 70.65% || Entropy: 0.630
Column "OUTCOME"	Μissing values: 100.00% || Entropy: 0.000
Column "RESPONSE"	Μissing values: 92.39% || Entropy: 1.946
Column "HELP_REASON"	Μissing values: 93.48% || Entropy: 1.792
Column "HELP_PROVIDER"	Μissing values: 94.57% || Entropy: 1.609
Column "OBS_VALUE"	Μissing values: 36.41% || Entropy: 5.851
Column "DATA_SOURCE"	Μissing values: 0.00% || Entropy: 1.450
Column "OBS_COMMENT"	Μissing values: 49.66% || Entropy: 1.790

In [190]:
dropList_enc = []

for col in data_enc_train.columns:
    ent = entropy(data_enc_train[col].value_counts())
    if ent == 0:
        dropList_enc.append(col)
        print(f'Column \"{col}\" entropy: {ent:.2f} || ADDED TO DROPLIST')
    else:
        print(f'Column \"{col}\" entropy: {ent:.2f}')

Column "TIME_PERIOD" entropy: 2.25
Column "GEO_PICT" entropy: 2.51
Column "TOPIC" entropy: 1.57
Column "CONDITION" entropy: 1.08
Column "VIOLENCE_TYPE" entropy: 1.00
Column "PERPETRATOR" entropy: 0.00 || ADDED TO DROPLIST
Column "ACTUALITY" entropy: 0.69
Column "LIFEPER" entropy: 0.00 || ADDED TO DROPLIST
Column "OUTCOME" entropy: 3.05
Column "RESPONSE" entropy: 0.00 || ADDED TO DROPLIST
Column "HELP_REASON" entropy: 0.00 || ADDED TO DROPLIST
Column "HELP_PROVIDER" entropy: 0.00 || ADDED TO DROPLIST
Column "OBS_VALUE" entropy: 5.22
Column "DATA_SOURCE" entropy: 1.45
Column "OBS_COMMENT" entropy: 1.80

In [191]:
data_enc_train.drop(dropList_enc, axis = 1, inplace = True)
data_enc_test.drop(dropList_enc, axis = 1, inplace = True)

In [192]:
printDFInfo(data_enc_train)

Column "TIME_PERIOD"	Μissing values: 0.00% || Entropy: 2.253
Column "GEO_PICT"	Μissing values: 0.00% || Entropy: 2.513
Column "TOPIC"		Μissing values: 0.00% || Entropy: 1.568
Column "CONDITION"	Μissing values: 52.94% || Entropy: 1.082
Column "VIOLENCE_TYPE"	Μissing values: 73.53% || Entropy: 0.995
Column "ACTUALITY"	Μissing values: 73.53% || Entropy: 0.687
Column "OUTCOME"	Μissing values: 0.00% || Entropy: 3.047
Column "OBS_VALUE"	Μissing values: 45.22% || Entropy: 5.223
Column "DATA_SOURCE"	Μissing values: 0.00% || Entropy: 1.450
Column "OBS_COMMENT"	Μissing values: 50.00% || Entropy: 1.800

In [193]:
printDFInfo(data_enc_test)

Column "TIME_PERIOD"	Μissing values: 0.00% || Entropy: 2.253
Column "GEO_PICT"	Μissing values: 0.00% || Entropy: 2.513
Column "TOPIC"		Μissing values: 0.00% || Entropy: 2.501
Column "CONDITION"	Μissing values: 52.17% || Entropy: 0.108
Column "VIOLENCE_TYPE"	Μissing values: 20.65% || Entropy: 2.819
Column "ACTUALITY"	Μissing values: 29.35% || Entropy: 0.692
Column "OUTCOME"	Μissing values: 100.00% || Entropy: 0.000
Column "OBS_VALUE"	Μissing values: 36.41% || Entropy: 5.851
Column "DATA_SOURCE"	Μissing values: 0.00% || Entropy: 1.450
Column "OBS_COMMENT"	Μissing values: 49.66% || Entropy: 1.790

In [194]:
#=============================================================================================================================
#IMPUTATION

In [195]:
print(data_enc_train.shape)
print(data_enc_train)
print(data_enc_test.shape)
print(data_enc_test)

(544, 10)
     TIME_PERIOD GEO_PICT TOPIC CONDITION VIOLENCE_TYPE ACTUALITY OUTCOME  \
0           2013      0.0  10.0       NaN           9.0       0.0    13.0
1           2013      0.0  10.0       NaN           9.0       1.0    13.0
2           2013      0.0  10.0       NaN          10.0       0.0    13.0
3           2013      0.0  10.0       NaN          10.0       0.0    15.0
4           2013      0.0  10.0       NaN          10.0       1.0    12.0
..           ...      ...   ...       ...           ...       ...     ...
539         2006     12.0  14.0       0.0           NaN       NaN     2.0
540         2006     12.0  14.0       0.0           NaN       NaN     3.0
541         2006     12.0  14.0       0.0           NaN       NaN     4.0
542         2006     12.0  14.0       0.0           NaN       NaN     5.0
543         2006     12.0  14.0       0.0           NaN       NaN     6.0

     OBS_VALUE DATA_SOURCE OBS_COMMENT
0          NaN         1.0         NaN
1         39.6         1.0         NaN
2          5.7         1.0         NaN
3          1.4         1.0         NaN
4         21.6         1.0         NaN
..         ...         ...         ...
539       12.1         1.0        15.0
540       13.1         1.0        15.0
541       34.9         1.0        15.0
542       32.3         1.0        15.0
543       24.3         1.0        15.0

[544 rows x 10 columns]
(1472, 10)
      TIME_PERIOD GEO_PICT TOPIC CONDITION VIOLENCE_TYPE ACTUALITY OUTCOME  \
0            2013      0.0   0.0       1.0           0.0       NaN     NaN
1            2013      0.0   0.0       1.0           5.0       0.0     NaN
2            2013      0.0   0.0       1.0           5.0       1.0     NaN
3            2013      0.0   0.0       1.0           9.0       0.0     NaN
4            2013      0.0   0.0       1.0           9.0       1.0     NaN
...           ...      ...   ...       ...           ...       ...     ...
1467         2006     12.0  17.0       NaN           NaN       NaN     NaN
1468         2006     12.0  17.0       NaN           NaN       NaN     NaN
1469         2006     12.0  17.0       NaN           NaN       NaN     NaN
1470         2006     12.0  17.0       NaN           NaN       NaN     NaN
1471         2006     12.0  17.0       NaN           NaN       NaN     NaN

      OBS_VALUE DATA_SOURCE OBS_COMMENT
0           6.2         1.0         NaN
1           9.6         1.0         NaN
2          26.7         1.0         NaN
3           6.7         1.0         NaN
4          30.2         1.0         NaN
...         ...         ...         ...
1467        NaN         1.0        15.0
1468        4.1         1.0        15.0
1469       10.0         1.0        15.0
1470        0.2         1.0        15.0
1471        1.0         1.0        15.0

[1472 rows x 10 columns]

In [196]:
#OBS_VALUE, DATA_SOURCE, OBS_COMMENT --> useless (?)

In [213]:
imp = SimpleImputer(strategy="most_frequent")
impt_train = imp.fit_transform(data_enc_train)
data_impt_train = pd.DataFrame(impt_train, columns=['TIME_PERIOD', 'GEO_PICT', 'TOPIC', 'CONDITION', 'VIOLENCE_TYPE', 'ACTUALITY', 'OUTCOME', 'OBS_VALUE', 'DATA_SOURCE', 'OBS_COMMENT'])
print(data_impt_train.shape)
print(data_impt_train)

(544, 10)
    TIME_PERIOD GEO_PICT TOPIC CONDITION VIOLENCE_TYPE ACTUALITY OUTCOME  \
0          2013      0.0  10.0       0.0           9.0       0.0    13.0
1          2013      0.0  10.0       0.0           9.0       1.0    13.0
2          2013      0.0  10.0       0.0          10.0       0.0    13.0
3          2013      0.0  10.0       0.0          10.0       0.0    15.0
4          2013      0.0  10.0       0.0          10.0       1.0    12.0
..          ...      ...   ...       ...           ...       ...     ...
539        2006     12.0  14.0       0.0          10.0       1.0     2.0
540        2006     12.0  14.0       0.0          10.0       1.0     3.0
541        2006     12.0  14.0       0.0          10.0       1.0     4.0
542        2006     12.0  14.0       0.0          10.0       1.0     5.0
543        2006     12.0  14.0       0.0          10.0       1.0     6.0

    OBS_VALUE DATA_SOURCE OBS_COMMENT
0         0.0         1.0        15.0
1        39.6         1.0        15.0
2         5.7         1.0        15.0
3         1.4         1.0        15.0
4        21.6         1.0        15.0
..        ...         ...         ...
539      12.1         1.0        15.0
540      13.1         1.0        15.0
541      34.9         1.0        15.0
542      32.3         1.0        15.0
543      24.3         1.0        15.0

[544 rows x 10 columns]

In [229]:
imp = SimpleImputer(strategy="most_frequent")
impt_test = imp.fit_transform(data_enc_test)
data_impt_test = pd.DataFrame(impt_test)
data_impt_test.insert(9, '9', 'NaN')
data_impt_test.columns= ['TIME_PERIOD', 'GEO_PICT', 'TOPIC', 'CONDITION', 'VIOLENCE_TYPE', 'ACTUALITY', 'OBS_VALUE', 'DATA_SOURCE', 'OBS_COMMENT', 'OUTCOME']

print(data_impt_test.shape)
print(data_impt_test)

(1472, 10)
     TIME_PERIOD GEO_PICT TOPIC CONDITION VIOLENCE_TYPE ACTUALITY OBS_VALUE  \
0           2013      0.0   0.0       1.0           0.0       1.0       6.2
1           2013      0.0   0.0       1.0           5.0       0.0       9.6
2           2013      0.0   0.0       1.0           5.0       1.0      26.7
3           2013      0.0   0.0       1.0           9.0       0.0       6.7
4           2013      0.0   0.0       1.0           9.0       1.0      30.2
...          ...      ...   ...       ...           ...       ...       ...
1467        2006     12.0  17.0       1.0           9.0       1.0       0.0
1468        2006     12.0  17.0       1.0           9.0       1.0       4.1
1469        2006     12.0  17.0       1.0           9.0       1.0      10.0
1470        2006     12.0  17.0       1.0           9.0       1.0       0.2
1471        2006     12.0  17.0       1.0           9.0       1.0       1.0

     DATA_SOURCE OBS_COMMENT OUTCOME
0            1.0        15.0     NaN
1            1.0        15.0     NaN
2            1.0        15.0     NaN
3            1.0        15.0     NaN
4            1.0        15.0     NaN
...          ...         ...     ...
1467         1.0        15.0     NaN
1468         1.0        15.0     NaN
1469         1.0        15.0     NaN
1470         1.0        15.0     NaN
1471         1.0        15.0     NaN

[1472 rows x 10 columns]

In [230]:
data_impt_train.to_csv("data_impt_train.csv", index = False)
data_impt_test.to_csv("data_impt_test.csv", index = False)

In [259]:
dataset = pd.read_csv('data_impt_train.csv')
dataset

,TIME_PERIOD,GEO_PICT,TOPIC,CONDITION,VIOLENCE_TYPE,ACTUALITY,OBS_VALUE,DATA_SOURCE,OBS_COMMENT,OUTCOME
0,2013,0.0,10.0,0.0,9.0,0.0,13.0,0.0,1.0,15.0
1,2013,0.0,10.0,0.0,9.0,1.0,13.0,39.6,1.0,15.0
2,2013,0.0,10.0,0.0,10.0,0.0,13.0,5.7,1.0,15.0
3,2013,0.0,10.0,0.0,10.0,0.0,15.0,1.4,1.0,15.0
4,2013,0.0,10.0,0.0,10.0,1.0,12.0,21.6,1.0,15.0
...,...,...,...,...,...,...,...,...,...,...
539,2006,12.0,14.0,0.0,10.0,1.0,2.0,12.1,1.0,15.0
540,2006,12.0,14.0,0.0,10.0,1.0,3.0,13.1,1.0,15.0
541,2006,12.0,14.0,0.0,10.0,1.0,4.0,34.9,1.0,15.0
542,2006,12.0,14.0,0.0,10.0,1.0,5.0,32.3,1.0,15.0
543,2006,12.0,14.0,0.0,10.0,1.0,6.0,24.3,1.0,15.0

In [260]:
#dataset.drop(columns='DATA_SOURCE', inplace = True)
#dataset.drop(columns='OBS_COMMENT', inplace = True)
#dataset

In [266]:
X = dataset.iloc[:, 0:8] 
y = dataset.iloc[:,9]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

In [267]:
sc= StandardScaler()
sc.fit(X_train)
X_train = sc.transform(X_train)
X_test = sc.transform(X_test)

In [268]:
MLP = MLPClassifier(hidden_layer_sizes=(100,100,100), activation='relu', solver='lbfgs', max_iter=100, random_state=0, tol=0.00001)
MLP.fit(X_train, y_train)
y_predicted = MLP.predict(X_test)

In [269]:
print("Recall: %2f" % metrics.recall_score(y_test, y_predicted, average = 'macro', zero_division=1))
print("Precision Score: %2f"% metrics.precision_score(y_test, y_predicted, average = 'macro', zero_division=1))
print("Accuracy: %2f" % metrics.accuracy_score(y_test, y_predicted))
print("F1: %2f" % metrics.f1_score(y_test, y_predicted, average ='macro'))

Recall: 0.684627
Precision Score: 0.895789
Accuracy: 0.963235
F1: 0.589634

In [270]:
SVM = svm.SVC(C=0.1, kernel= 'poly', gamma=0.2, degree=2)
SVM.fit(X_train, y_train.ravel())
y_predicted = SVM.predict(X_test)

In [271]:
print("Accuracy: %2f" % metrics.accuracy_score(y_test, y_predicted))
print("Recall: %2f" % metrics.recall_score(y_test, y_predicted, average = 'macro'))
print("Precision Score: %2f"% metrics.precision_score(y_test, y_predicted, average = 'macro'))
print("F1 score: %2f"% metrics.f1_score(y_test, y_predicted, average='macro'))

Accuracy: 0.676471
Recall: 0.111111
Precision Score: 0.075163
F1 score: 0.089669

In [273]:
KNN_model = KNeighborsClassifier(n_neighbors=1, weights="distance", metric="minkowski", p=2 )
KNN_model.fit(X_train, y_train)
y_predicted = KNN_model.predict(X_test)

In [274]:
print("Accuracy: %2f" % metrics.accuracy_score(y_test, y_predicted))
print("Recall: %2f" % metrics.recall_score(y_test, y_predicted, average = 'macro'))
print("Precision Score: %2f"% metrics.precision_score(y_test, y_predicted, average = 'macro'))
print("F1 score: %2f"% metrics.f1_score(y_test, y_predicted, average='macro'))

Accuracy: 0.860294
Recall: 0.434497
Precision Score: 0.442635
F1 score: 0.429906